#!/usr/bin/env bash

set -e

echo "▶️  Downloading some required Docker images (wait some seconds/minutes while downloading)..."
docker pull --quiet ph3nol/freqtrade:latest
docker pull --quiet ph3nol/freqtrade-ui:latest
docker pull --quiet ph3nol/freqtrade-manager:latest

echo "▶️  Downloading/Installing Trading Bot..."
curl -sSL -o /usr/local/bin/bot https://raw.githubusercontent.com/Ph3nol/Trading-Bot/bot

echo ""
echo "✅ Your Trading Bot is now ready! 🚀🔥"
